# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        Get-Date
        $ErrorActionPreference = "Stop"
install:
  ps: |
        Import-Module '.\scripts\appveyor-tool.ps1'
        Bootstrap

# Adapt as necessary starting from here

platform: x64

environment:
  global:
    R_VERSION: release
    R_ARCH: x64
    NOT_CRAN: 'true'

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
