on:
  pull_request:
    branches:
      - master

name: R-CMD-check non-master
permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: macOS-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          needs: check
          extra-packages: |
            any::rcmdcheck
            any::bigmemory

      - uses: r-lib/actions/setup-tinytex@v2

      - name: Install Yihui packages
        run: |
          Rscript -e 'tinytex:::install_yihui_pkgs()'

      - uses: r-lib/actions/check-r-package@v2
        with:
          build_args: 'c("--compact-vignettes=both", "--no-manual")'
          upload-snapshots: true
        continue-on-error: ${{ matrix.config.r == 'devel' }}

      - name: Test coverage
        if: runner.os == 'Linux' && matrix.config.r == 'release'
        run: |
          Rscript -e 'install.packages("covr")'
          Rscript codecov.R
        continue-on-error: true
